name: Learn Github Actions

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]
  
jobs:
  learn-github-actions:
    runs-on: ubuntu-latest

    steps:
    
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Check if event is PR
      if: ${{ github.event_name }} == "pull_request"
      run: echo "IMAGE_TAG=dev"
      env:
        IMAGE_TAG: dev

    # - name: Check if event is push
    #   if: ${{ github.event_name }} == "push"
    #   run: echo "IMAGE_TAG=latest"
    #   env:
    #     IMAGE_TAG: latest

    - name: Echo env var
      run: |
        echo "Tagging image as ${{ env.IMAGE_TAG }}"
        echo "Tagging image as $IMAGE_TAG"
